// AUTO-GENERATED by scripts/generate-tile-manifest.mjs — do not edit by hand.
// Maps a TileKind to the file extension of its real artwork in public/tiles/.
import type { TileKind } from "@/lib/questions/types";

export const REAL_TILE_FILES: Partial<Record<TileKind, "svg" | "png" | "webp">> = {
  "corner": "svg",
  "crossroad": "svg",
  "grass": "svg",
  "narrow-residential": "svg",
  "roundabout-center": "svg",
  "straight": "svg",
  "t-junction": "svg",
  "wide-curve": "svg",
};
