// AUTO-GENERATED by scripts/generate-scene-manifest.mjs — do not edit by hand.
// Source of truth: the "module-slots" marker layer inside each
// public/scenes/{locationId}.svg — move a marker there and re-run
// `npm run scenes:manifest` to pick it up here.

export type ActorSlot = { x: number; y: number; rotation: number; scale: number; bearing: number };
export type SignSlot = { x: number; y: number };
export type RingGeometry = { x: number; y: number; approachRadius: number; ringRadius: number; laneOffset: number; ringLeadDeg: number };

export const LOCATION_ACTOR_SLOTS: Record<string, Record<string, ActorSlot>> = {
  "doorgaande-weg-twee-zijwegen-zonder-naad": {
    "north": {"x":462,"y":180,"rotation":180,"scale":2,"bearing":0},
    "south": {"x":562,"y":844,"rotation":0,"scale":2,"bearing":180},
    "west": {"x":100,"y":572,"rotation":90,"scale":2,"bearing":270},
    "east": {"x":924,"y":452,"rotation":270,"scale":2,"bearing":90},
  },
  "eenbaansrotonde": {
    "north": {"x":455,"y":162,"rotation":180,"scale":2,"bearing":0},
    "south": {"x":569,"y":862,"rotation":0,"scale":2,"bearing":180},
    "west": {"x":162,"y":569,"rotation":90,"scale":2,"bearing":270},
    "east": {"x":862,"y":455,"rotation":270,"scale":2,"bearing":90},
  },
  "gelijkwaardige-kruising": {
    "north": {"x":434,"y":180,"rotation":180,"scale":2,"bearing":0},
    "south": {"x":590,"y":844,"rotation":0,"scale":2,"bearing":180},
    "west": {"x":180,"y":590,"rotation":90,"scale":2,"bearing":270},
    "east": {"x":844,"y":434,"rotation":270,"scale":2,"bearing":90},
  },
  "straat-van-rechts-stedelijk": {
    "north": {"x":436,"y":150,"rotation":180,"scale":2,"bearing":0},
    "south": {"x":588,"y":874,"rotation":0,"scale":2,"bearing":180},
    "east": {"x":900,"y":436,"rotation":270,"scale":2,"bearing":90},
  },
};

export const LOCATION_SIGN_SLOTS: Record<string, Record<string, SignSlot>> = {
  "doorgaande-weg-twee-zijwegen-zonder-naad": {
    "north": {"x":360,"y":110},
    "south": {"x":664,"y":914},
    "west": {"x":110,"y":680},
    "east": {"x":914,"y":344},
  },
  "eenbaansrotonde": {
    "north": {"x":340,"y":130},
    "south": {"x":684,"y":894},
    "west": {"x":130,"y":684},
    "east": {"x":894,"y":340},
  },
  "gelijkwaardige-kruising": {
    "north": {"x":300,"y":110},
    "south": {"x":724,"y":914},
    "west": {"x":110,"y":724},
    "east": {"x":914,"y":300},
  },
  "straat-van-rechts-stedelijk": {
    "north": {"x":300,"y":90},
    "south": {"x":664,"y":934},
    "east": {"x":934,"y":300},
  },
};

export const LOCATION_RING_GEOMETRY: Record<string, RingGeometry> = {
  "eenbaansrotonde": {"x":512,"y":512,"approachRadius":350,"ringRadius":187,"laneOffset":57,"ringLeadDeg":26},
};
